Feb 03, 2016 12:19:14 AM jdrivetrack.DerbyDatabase reportException
WARNING: Exception
java.sql.SQLDataException: The resulting value is outside the range for the data type DOUBLE.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setDouble(Unknown Source)
	at jdrivetrack.UTMTestTile.getAppendPreparedSatatement(UTMTestTile.java:355)
	at jdrivetrack.DerbyDatabase$AppendTileDataRecord.run(DerbyDatabase.java:274)
	at java.lang.Thread.run(Unknown Source)
Caused by: ERROR 22003: The resulting value is outside the range for the data type DOUBLE.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.NumberDataType.normalizeDOUBLE(Unknown Source)
	at org.apache.derby.iapi.types.SQLDouble.setValue(Unknown Source)
	... 4 more

Feb 03, 2016 12:19:24 AM jdrivetrack.DerbyDatabase reportException
WARNING: Exception
java.sql.SQLDataException: The resulting value is outside the range for the data type DOUBLE.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setDouble(Unknown Source)
	at jdrivetrack.UTMTestTile.getAppendPreparedSatatement(UTMTestTile.java:355)
	at jdrivetrack.DerbyDatabase$AppendTileDataRecord.run(DerbyDatabase.java:274)
	at java.lang.Thread.run(Unknown Source)
Caused by: ERROR 22003: The resulting value is outside the range for the data type DOUBLE.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.NumberDataType.normalizeDOUBLE(Unknown Source)
	at org.apache.derby.iapi.types.SQLDouble.setValue(Unknown Source)
	... 4 more

Feb 03, 2016 12:19:27 AM jdrivetrack.DerbyDatabase reportException
WARNING: Exception
java.sql.SQLDataException: The resulting value is outside the range for the data type DOUBLE.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setDouble(Unknown Source)
	at jdrivetrack.UTMTestTile.getAppendPreparedSatatement(UTMTestTile.java:355)
	at jdrivetrack.DerbyDatabase$AppendTileDataRecord.run(DerbyDatabase.java:274)
	at java.lang.Thread.run(Unknown Source)
Caused by: ERROR 22003: The resulting value is outside the range for the data type DOUBLE.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.NumberDataType.normalizeDOUBLE(Unknown Source)
	at org.apache.derby.iapi.types.SQLDouble.setValue(Unknown Source)
	... 4 more

